dist: xenial
language: go
go:
  - 1.13.x

go_import_path: github.com/application-stacks/operator
env:
  - GO111MODULE=on

services:
  - docker

stages:
  - name: test
  - name: build
  - name: build manifest

jobs:
  include:
    - name: Unit testing
      stage: test
      script:
        - make unit-test
    - name: Build image and E2E test
      script:
        - make test-e2e
    ## if master branch build and push images on all three archs
    ## the below will all run in parallel as they're the same stage
    - name: Build image on amd64
      stage: build
      os: linux
      arch: amd64
      script:
        - make build-multiarch-image
        - make build-manifest
      if: branch = master AND fork = false AND type != pull_request
    - name: Build image on ppc64le
      stage: build
      os: linux
      arch: ppc64le
      script:
        - make build-multiarch-image
        - make build-manifest
      if: branch = master AND fork = false AND type != pull_request
    - name: Build image on s390x
      stage: build
      os: linux
      arch: s390x
      script:
        - make build-multiarch-image
        - make build-manifest
      if: branch = master AND fork = false AND type != pull_request
    ## in case there were concurrency issues with building manifest lists
    ## in previous steps, create FAT manifests one last time
    - name: Verify manifest lists
      stage: build manifest
      script:
        - make build-manifest
      if: branch = master AND fork = false AND type != pull_request
