kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runtime-component-operator
subjects:
- kind: ServiceAccount
  name: runtime-component-operator
  namespace: RUNTIME_COMPONENT_OPERATOR_NAMESPACE
roleRef:
  kind: ClusterRole
  name: runtime-component-operator
  apiGroup: rbac.authorization.k8s.io
